require 'minitest/autorun'
require './code'

class AoCDay03Test < Minitest::Test
  def test_task_01
    aoc_day03 = AoCDay03.new('467..114..
                              ...*......
                              ..35..633.
                              ......#...
                              617*......
                              .....+.58.
                              ..592.....
                              ......755.
                              ...$.*....
                              .664.598..')
    assert_equal aoc_day03.task_01, 4361
  end

  def test_task_02
    aoc_day03 = AoCDay03.new('467..114..
                              ...*......
                              ..35..633.
                              ......#...
                              617*......
                              .....+.58.
                              ..592.....
                              ......755.
                              ...$.*....
                              .664.598..')
    assert_equal aoc_day03.task_02, 467835
  end
end
